version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 300184973710.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t yamlvalidator-registry .
      - docker tag yamlvalidator-registry:latest 300184973710.dkr.ecr.ap-south-1.amazonaws.com/yamlvalidator-registry:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 300184973710.dkr.ecr.ap-south-1.amazonaws.com/yamlvalidator-registry:latest
      - echo Writing image definitions file...
      - printf '[{"name":"yaml-validator","imageUri":"%s"}]' "300184973710.dkr.ecr.ap-south-1.amazonaws.com/yamlvalidator-registry:latest" > imagedefinitions.json
      - echo Writing image definitions file...
      # add your container name
      - DOCKER_CONTAINER_NAME=yamlvalidator-registry
      - printf '[{"name":"%s","imageUri":"%s"}]' "300184973710.dkr.ecr.ap-south-1.amazonaws.com/yamlvalidator-registry:latest" > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/yamlvalidator-0.0.1-SNAPSHOT.jar

